/*
 * generated by Xtext 2.25.0
 */
package com.ktsv.asl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.ktsv.asl.ide.contentassist.antlr.internal.InternalAslParser;
import com.ktsv.asl.services.AslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSpatialEntityAccess().getAlternatives(), "rule__SpatialEntity__Alternatives");
			builder.put(grammarAccess.getPlanAccess().getAlternatives(), "rule__Plan__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getABModelAccess().getGroup(), "rule__ABModel__Group__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_2(), "rule__ABModel__Group_2__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_3(), "rule__ABModel__Group_3__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_4(), "rule__ABModel__Group_4__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_5(), "rule__ABModel__Group_5__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_6(), "rule__ABModel__Group_6__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_12(), "rule__ABModel__Group_12__0");
			builder.put(grammarAccess.getABModelAccess().getGroup_17(), "rule__ABModel__Group_17__0");
			builder.put(grammarAccess.getGlobalBlockAccess().getGroup(), "rule__GlobalBlock__Group__0");
			builder.put(grammarAccess.getGlobalBlockAccess().getGroup_3(), "rule__GlobalBlock__Group_3__0");
			builder.put(grammarAccess.getGlobalBlockAccess().getGroup_7(), "rule__GlobalBlock__Group_7__0");
			builder.put(grammarAccess.getGlobalBlockAccess().getGroup_12(), "rule__GlobalBlock__Group_12__0");
			builder.put(grammarAccess.getAgentBlockAccess().getGroup(), "rule__AgentBlock__Group__0");
			builder.put(grammarAccess.getAgentBlockAccess().getGroup_4(), "rule__AgentBlock__Group_4__0");
			builder.put(grammarAccess.getAgentBlockAccess().getGroup_5(), "rule__AgentBlock__Group_5__0");
			builder.put(grammarAccess.getAgentBlockAccess().getGroup_6(), "rule__AgentBlock__Group_6__0");
			builder.put(grammarAccess.getAgentBlockAccess().getGroup_10(), "rule__AgentBlock__Group_10__0");
			builder.put(grammarAccess.getAgentBlockAccess().getGroup_15(), "rule__AgentBlock__Group_15__0");
			builder.put(grammarAccess.getExperimentBlockAccess().getGroup(), "rule__ExperimentBlock__Group__0");
			builder.put(grammarAccess.getExperimentBlockAccess().getGroup_2(), "rule__ExperimentBlock__Group_2__0");
			builder.put(grammarAccess.getExperimentBlockAccess().getGroup_3(), "rule__ExperimentBlock__Group_3__0");
			builder.put(grammarAccess.getExperimentBlockAccess().getGroup_7(), "rule__ExperimentBlock__Group_7__0");
			builder.put(grammarAccess.getExperimentBlockAccess().getGroup_12(), "rule__ExperimentBlock__Group_12__0");
			builder.put(grammarAccess.getGlobalVariableAccess().getGroup(), "rule__GlobalVariable__Group__0");
			builder.put(grammarAccess.getGlobalVariableAccess().getGroup_4(), "rule__GlobalVariable__Group_4__0");
			builder.put(grammarAccess.getGlobalVariableAccess().getGroup_5(), "rule__GlobalVariable__Group_5__0");
			builder.put(grammarAccess.getGlobalVariableAccess().getGroup_6(), "rule__GlobalVariable__Group_6__0");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getGroup(), "rule__SpatialEntity_Impl__Group__0");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getGroup_3(), "rule__SpatialEntity_Impl__Group_3__0");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getGroup_4(), "rule__SpatialEntity_Impl__Group_4__0");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getGroup_5(), "rule__SpatialEntity_Impl__Group_5__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getPolygonAccess().getGroup(), "rule__Polygon__Group__0");
			builder.put(grammarAccess.getPolygonAccess().getGroup_3(), "rule__Polygon__Group_3__0");
			builder.put(grammarAccess.getPolygonAccess().getGroup_4(), "rule__Polygon__Group_4__0");
			builder.put(grammarAccess.getPolygonAccess().getGroup_5(), "rule__Polygon__Group_5__0");
			builder.put(grammarAccess.getLineAccess().getGroup(), "rule__Line__Group__0");
			builder.put(grammarAccess.getLineAccess().getGroup_3(), "rule__Line__Group_3__0");
			builder.put(grammarAccess.getLineAccess().getGroup_4(), "rule__Line__Group_4__0");
			builder.put(grammarAccess.getLineAccess().getGroup_5(), "rule__Line__Group_5__0");
			builder.put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
			builder.put(grammarAccess.getPointAccess().getGroup_3(), "rule__Point__Group_3__0");
			builder.put(grammarAccess.getPointAccess().getGroup_4(), "rule__Point__Group_4__0");
			builder.put(grammarAccess.getPointAccess().getGroup_5(), "rule__Point__Group_5__0");
			builder.put(grammarAccess.getPlan_ImplAccess().getGroup(), "rule__Plan_Impl__Group__0");
			builder.put(grammarAccess.getPlan_ImplAccess().getGroup_3(), "rule__Plan_Impl__Group_3__0");
			builder.put(grammarAccess.getPlan_ImplAccess().getGroup_4(), "rule__Plan_Impl__Group_4__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_3(), "rule__Property__Group_3__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_4(), "rule__Property__Group_4__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_5(), "rule__Property__Group_5__0");
			builder.put(grammarAccess.getSimplePlanAccess().getGroup(), "rule__SimplePlan__Group__0");
			builder.put(grammarAccess.getSimplePlanAccess().getGroup_3(), "rule__SimplePlan__Group_3__0");
			builder.put(grammarAccess.getSimplePlanAccess().getGroup_4(), "rule__SimplePlan__Group_4__0");
			builder.put(grammarAccess.getReflexAccess().getGroup(), "rule__Reflex__Group__0");
			builder.put(grammarAccess.getReflexAccess().getGroup_5(), "rule__Reflex__Group_5__0");
			builder.put(grammarAccess.getComplexePlanAccess().getGroup(), "rule__ComplexePlan__Group__0");
			builder.put(grammarAccess.getComplexePlanAccess().getGroup_3(), "rule__ComplexePlan__Group_3__0");
			builder.put(grammarAccess.getComplexePlanAccess().getGroup_4(), "rule__ComplexePlan__Group_4__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_3(), "rule__Parameter__Group_3__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_4(), "rule__Parameter__Group_4__0");
			builder.put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
			builder.put(grammarAccess.getOutputAccess().getGroup_2(), "rule__Output__Group_2__0");
			builder.put(grammarAccess.getOutputAccess().getGroup_6(), "rule__Output__Group_6__0");
			builder.put(grammarAccess.getOutputAccess().getGroup_11(), "rule__Output__Group_11__0");
			builder.put(grammarAccess.getOutputAccess().getGroup_16(), "rule__Output__Group_16__0");
			builder.put(grammarAccess.getOutputAccess().getGroup_21(), "rule__Output__Group_21__0");
			builder.put(grammarAccess.getMonitorAccess().getGroup(), "rule__Monitor__Group__0");
			builder.put(grammarAccess.getMonitorAccess().getGroup_3(), "rule__Monitor__Group_3__0");
			builder.put(grammarAccess.getMonitorAccess().getGroup_4(), "rule__Monitor__Group_4__0");
			builder.put(grammarAccess.getDisplayAccess().getGroup(), "rule__Display__Group__0");
			builder.put(grammarAccess.getDisplayAccess().getGroup_3(), "rule__Display__Group_3__0");
			builder.put(grammarAccess.getDisplayAccess().getGroup_4(), "rule__Display__Group_4__0");
			builder.put(grammarAccess.getExportFileAccess().getGroup(), "rule__ExportFile__Group__0");
			builder.put(grammarAccess.getExportFileAccess().getGroup_3(), "rule__ExportFile__Group_3__0");
			builder.put(grammarAccess.getInspectorAccess().getGroup(), "rule__Inspector__Group__0");
			builder.put(grammarAccess.getInspectorAccess().getGroup_3(), "rule__Inspector__Group_3__0");
			builder.put(grammarAccess.getInspectorAccess().getGroup_4(), "rule__Inspector__Group_4__0");
			builder.put(grammarAccess.getInspectorAccess().getGroup_5(), "rule__Inspector__Group_5__0");
			builder.put(grammarAccess.getABModelAccess().getModelNameAssignment_2_1(), "rule__ABModel__ModelNameAssignment_2_1");
			builder.put(grammarAccess.getABModelAccess().getDescriptionAssignment_3_1(), "rule__ABModel__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getABModelAccess().getKeywordsAssignment_4_1(), "rule__ABModel__KeywordsAssignment_4_1");
			builder.put(grammarAccess.getABModelAccess().getAuthorAssignment_5_1(), "rule__ABModel__AuthorAssignment_5_1");
			builder.put(grammarAccess.getABModelAccess().getCreateOnAssignment_6_1(), "rule__ABModel__CreateOnAssignment_6_1");
			builder.put(grammarAccess.getABModelAccess().getContainsGAssignment_8(), "rule__ABModel__ContainsGAssignment_8");
			builder.put(grammarAccess.getABModelAccess().getContainsSAssignment_11(), "rule__ABModel__ContainsSAssignment_11");
			builder.put(grammarAccess.getABModelAccess().getContainsSAssignment_12_1(), "rule__ABModel__ContainsSAssignment_12_1");
			builder.put(grammarAccess.getABModelAccess().getContainsEAssignment_16(), "rule__ABModel__ContainsEAssignment_16");
			builder.put(grammarAccess.getABModelAccess().getContainsEAssignment_17_1(), "rule__ABModel__ContainsEAssignment_17_1");
			builder.put(grammarAccess.getGlobalBlockAccess().getInitAssignment_0(), "rule__GlobalBlock__InitAssignment_0");
			builder.put(grammarAccess.getGlobalBlockAccess().getIdAssignment_3_1(), "rule__GlobalBlock__IdAssignment_3_1");
			builder.put(grammarAccess.getGlobalBlockAccess().getContainsGlAssignment_6(), "rule__GlobalBlock__ContainsGlAssignment_6");
			builder.put(grammarAccess.getGlobalBlockAccess().getContainsGlAssignment_7_1(), "rule__GlobalBlock__ContainsGlAssignment_7_1");
			builder.put(grammarAccess.getGlobalBlockAccess().getContainsSEAssignment_11(), "rule__GlobalBlock__ContainsSEAssignment_11");
			builder.put(grammarAccess.getGlobalBlockAccess().getContainsSEAssignment_12_1(), "rule__GlobalBlock__ContainsSEAssignment_12_1");
			builder.put(grammarAccess.getAgentBlockAccess().getInitAssignment_0(), "rule__AgentBlock__InitAssignment_0");
			builder.put(grammarAccess.getAgentBlockAccess().getAspectFunctionAssignment_1(), "rule__AgentBlock__AspectFunctionAssignment_1");
			builder.put(grammarAccess.getAgentBlockAccess().getNameAgentAssignment_4_1(), "rule__AgentBlock__NameAgentAssignment_4_1");
			builder.put(grammarAccess.getAgentBlockAccess().getAspectNameAssignment_5_1(), "rule__AgentBlock__AspectNameAssignment_5_1");
			builder.put(grammarAccess.getAgentBlockAccess().getColorAssignment_6_1(), "rule__AgentBlock__ColorAssignment_6_1");
			builder.put(grammarAccess.getAgentBlockAccess().getHasPAssignment_9(), "rule__AgentBlock__HasPAssignment_9");
			builder.put(grammarAccess.getAgentBlockAccess().getHasPAssignment_10_1(), "rule__AgentBlock__HasPAssignment_10_1");
			builder.put(grammarAccess.getAgentBlockAccess().getHasPrAssignment_14(), "rule__AgentBlock__HasPrAssignment_14");
			builder.put(grammarAccess.getAgentBlockAccess().getHasPrAssignment_15_1(), "rule__AgentBlock__HasPrAssignment_15_1");
			builder.put(grammarAccess.getExperimentBlockAccess().getTypeAssignment_2_1(), "rule__ExperimentBlock__TypeAssignment_2_1");
			builder.put(grammarAccess.getExperimentBlockAccess().getExpNameAssignment_3_1(), "rule__ExperimentBlock__ExpNameAssignment_3_1");
			builder.put(grammarAccess.getExperimentBlockAccess().getHasPaAssignment_6(), "rule__ExperimentBlock__HasPaAssignment_6");
			builder.put(grammarAccess.getExperimentBlockAccess().getHasPaAssignment_7_1(), "rule__ExperimentBlock__HasPaAssignment_7_1");
			builder.put(grammarAccess.getExperimentBlockAccess().getOutputAssignment_11(), "rule__ExperimentBlock__OutputAssignment_11");
			builder.put(grammarAccess.getExperimentBlockAccess().getOutputAssignment_12_1(), "rule__ExperimentBlock__OutputAssignment_12_1");
			builder.put(grammarAccess.getGlobalVariableAccess().getInitAssignment_1(), "rule__GlobalVariable__InitAssignment_1");
			builder.put(grammarAccess.getGlobalVariableAccess().getGvarNameAssignment_4_1(), "rule__GlobalVariable__GvarNameAssignment_4_1");
			builder.put(grammarAccess.getGlobalVariableAccess().getTypeAssignment_5_1(), "rule__GlobalVariable__TypeAssignment_5_1");
			builder.put(grammarAccess.getGlobalVariableAccess().getInitValueAssignment_6_1(), "rule__GlobalVariable__InitValueAssignment_6_1");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getShapeNameAssignment_3_1(), "rule__SpatialEntity_Impl__ShapeNameAssignment_3_1");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getShapePathAssignment_4_1(), "rule__SpatialEntity_Impl__ShapePathAssignment_4_1");
			builder.put(grammarAccess.getSpatialEntity_ImplAccess().getTypeAssignment_5_1(), "rule__SpatialEntity_Impl__TypeAssignment_5_1");
			builder.put(grammarAccess.getPolygonAccess().getShapeNameAssignment_3_1(), "rule__Polygon__ShapeNameAssignment_3_1");
			builder.put(grammarAccess.getPolygonAccess().getShapePathAssignment_4_1(), "rule__Polygon__ShapePathAssignment_4_1");
			builder.put(grammarAccess.getPolygonAccess().getTypeAssignment_5_1(), "rule__Polygon__TypeAssignment_5_1");
			builder.put(grammarAccess.getLineAccess().getShapeNameAssignment_3_1(), "rule__Line__ShapeNameAssignment_3_1");
			builder.put(grammarAccess.getLineAccess().getShapePathAssignment_4_1(), "rule__Line__ShapePathAssignment_4_1");
			builder.put(grammarAccess.getLineAccess().getTypeAssignment_5_1(), "rule__Line__TypeAssignment_5_1");
			builder.put(grammarAccess.getPointAccess().getShapeNameAssignment_3_1(), "rule__Point__ShapeNameAssignment_3_1");
			builder.put(grammarAccess.getPointAccess().getShapePathAssignment_4_1(), "rule__Point__ShapePathAssignment_4_1");
			builder.put(grammarAccess.getPointAccess().getTypeAssignment_5_1(), "rule__Point__TypeAssignment_5_1");
			builder.put(grammarAccess.getPlan_ImplAccess().getPlanNameAssignment_3_1(), "rule__Plan_Impl__PlanNameAssignment_3_1");
			builder.put(grammarAccess.getPlan_ImplAccess().getIntentionAssignment_4_1(), "rule__Plan_Impl__IntentionAssignment_4_1");
			builder.put(grammarAccess.getPropertyAccess().getNameofvariableAssignment_3_1(), "rule__Property__NameofvariableAssignment_3_1");
			builder.put(grammarAccess.getPropertyAccess().getAssociateValueAssignment_4_1(), "rule__Property__AssociateValueAssignment_4_1");
			builder.put(grammarAccess.getPropertyAccess().getDefaultTypeAssignment_5_1(), "rule__Property__DefaultTypeAssignment_5_1");
			builder.put(grammarAccess.getSimplePlanAccess().getPlanNameAssignment_3_1(), "rule__SimplePlan__PlanNameAssignment_3_1");
			builder.put(grammarAccess.getSimplePlanAccess().getReturnTypeAssignment_4_1(), "rule__SimplePlan__ReturnTypeAssignment_4_1");
			builder.put(grammarAccess.getReflexAccess().getExistReflexAssignment_1(), "rule__Reflex__ExistReflexAssignment_1");
			builder.put(grammarAccess.getReflexAccess().getGoalAssignment_2(), "rule__Reflex__GoalAssignment_2");
			builder.put(grammarAccess.getReflexAccess().getPlanNameAssignment_5_1(), "rule__Reflex__PlanNameAssignment_5_1");
			builder.put(grammarAccess.getComplexePlanAccess().getPlanNameAssignment_3_1(), "rule__ComplexePlan__PlanNameAssignment_3_1");
			builder.put(grammarAccess.getComplexePlanAccess().getReturnTypeAssignment_4_1(), "rule__ComplexePlan__ReturnTypeAssignment_4_1");
			builder.put(grammarAccess.getParameterAccess().getParamNameAssignment_3_1(), "rule__Parameter__ParamNameAssignment_3_1");
			builder.put(grammarAccess.getParameterAccess().getTargetVariableAssignment_4_1(), "rule__Parameter__TargetVariableAssignment_4_1");
			builder.put(grammarAccess.getOutputAccess().getIdAssignment_2_1(), "rule__Output__IdAssignment_2_1");
			builder.put(grammarAccess.getOutputAccess().getHasMAssignment_5(), "rule__Output__HasMAssignment_5");
			builder.put(grammarAccess.getOutputAccess().getHasMAssignment_6_1(), "rule__Output__HasMAssignment_6_1");
			builder.put(grammarAccess.getOutputAccess().getContainsDAssignment_10(), "rule__Output__ContainsDAssignment_10");
			builder.put(grammarAccess.getOutputAccess().getContainsDAssignment_11_1(), "rule__Output__ContainsDAssignment_11_1");
			builder.put(grammarAccess.getOutputAccess().getHasEFAssignment_15(), "rule__Output__HasEFAssignment_15");
			builder.put(grammarAccess.getOutputAccess().getHasEFAssignment_16_1(), "rule__Output__HasEFAssignment_16_1");
			builder.put(grammarAccess.getOutputAccess().getHasIAssignment_20(), "rule__Output__HasIAssignment_20");
			builder.put(grammarAccess.getOutputAccess().getHasIAssignment_21_1(), "rule__Output__HasIAssignment_21_1");
			builder.put(grammarAccess.getMonitorAccess().getLabelAssignment_3_1(), "rule__Monitor__LabelAssignment_3_1");
			builder.put(grammarAccess.getMonitorAccess().getTargetVarAssignment_4_1(), "rule__Monitor__TargetVarAssignment_4_1");
			builder.put(grammarAccess.getDisplayAccess().getDisplayNameAssignment_3_1(), "rule__Display__DisplayNameAssignment_3_1");
			builder.put(grammarAccess.getDisplayAccess().getDisplayTypeAssignment_4_1(), "rule__Display__DisplayTypeAssignment_4_1");
			builder.put(grammarAccess.getExportFileAccess().getFileNameAssignment_3_1(), "rule__ExportFile__FileNameAssignment_3_1");
			builder.put(grammarAccess.getInspectorAccess().getInspectorNameAssignment_3_1(), "rule__Inspector__InspectorNameAssignment_3_1");
			builder.put(grammarAccess.getInspectorAccess().getAgentValueAssignment_4_1(), "rule__Inspector__AgentValueAssignment_4_1");
			builder.put(grammarAccess.getInspectorAccess().getTypeAssignment_5_1(), "rule__Inspector__TypeAssignment_5_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AslGrammarAccess grammarAccess;

	@Override
	protected InternalAslParser createParser() {
		InternalAslParser result = new InternalAslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
