/*
 * generated by Xtext 2.25.0
 */
package com.ktsv.asl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAslScopeProvider extends DelegatingScopeProvider {
}
