/*
 * generated by Xtext 2.25.0
 */
package com.ktsv.asl.parser.antlr;

import com.google.inject.Inject;
import com.ktsv.asl.parser.antlr.internal.InternalAslParser;
import com.ktsv.asl.services.AslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AslParser extends AbstractAntlrParser {

	@Inject
	private AslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAslParser createParser(XtextTokenStream stream) {
		return new InternalAslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ABModel";
	}

	public AslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
