/**
 */
package eclipse.emf.abmodel.model.abmodel.provider;

import eclipse.emf.abmodel.model.abmodel.util.AbmodelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AbmodelItemProviderAdapterFactory extends AbmodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AbmodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.ABModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ABModelItemProvider abModelItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.ABModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createABModelAdapter() {
		if (abModelItemProvider == null) {
			abModelItemProvider = new ABModelItemProvider(this);
		}

		return abModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.AgentBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AgentBlockItemProvider agentBlockItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.AgentBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAgentBlockAdapter() {
		if (agentBlockItemProvider == null) {
			agentBlockItemProvider = new AgentBlockItemProvider(this);
		}

		return agentBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.simplePlan} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected simplePlanItemProvider simplePlanItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.simplePlan}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsimplePlanAdapter() {
		if (simplePlanItemProvider == null) {
			simplePlanItemProvider = new simplePlanItemProvider(this);
		}

		return simplePlanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.GlobalBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalBlockItemProvider globalBlockItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.GlobalBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalBlockAdapter() {
		if (globalBlockItemProvider == null) {
			globalBlockItemProvider = new GlobalBlockItemProvider(this);
		}

		return globalBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.GlobalVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalVariableItemProvider globalVariableItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.GlobalVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalVariableAdapter() {
		if (globalVariableItemProvider == null) {
			globalVariableItemProvider = new GlobalVariableItemProvider(this);
		}

		return globalVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Output} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputItemProvider outputItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Output}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputAdapter() {
		if (outputItemProvider == null) {
			outputItemProvider = new OutputItemProvider(this);
		}

		return outputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Display} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisplayItemProvider displayItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Display}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisplayAdapter() {
		if (displayItemProvider == null) {
			displayItemProvider = new DisplayItemProvider(this);
		}

		return displayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Plan} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlanItemProvider planItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Plan}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlanAdapter() {
		if (planItemProvider == null) {
			planItemProvider = new PlanItemProvider(this);
		}

		return planItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Monitor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MonitorItemProvider monitorItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Monitor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMonitorAdapter() {
		if (monitorItemProvider == null) {
			monitorItemProvider = new MonitorItemProvider(this);
		}

		return monitorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.ExperimentBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExperimentBlockItemProvider experimentBlockItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.ExperimentBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExperimentBlockAdapter() {
		if (experimentBlockItemProvider == null) {
			experimentBlockItemProvider = new ExperimentBlockItemProvider(this);
		}

		return experimentBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Reflex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReflexItemProvider reflexItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Reflex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReflexAdapter() {
		if (reflexItemProvider == null) {
			reflexItemProvider = new ReflexItemProvider(this);
		}

		return reflexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.ComplexePlan} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplexePlanItemProvider complexePlanItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.ComplexePlan}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComplexePlanAdapter() {
		if (complexePlanItemProvider == null) {
			complexePlanItemProvider = new ComplexePlanItemProvider(this);
		}

		return complexePlanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.ExportFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExportFileItemProvider exportFileItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.ExportFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExportFileAdapter() {
		if (exportFileItemProvider == null) {
			exportFileItemProvider = new ExportFileItemProvider(this);
		}

		return exportFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Inspector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InspectorItemProvider inspectorItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Inspector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInspectorAdapter() {
		if (inspectorItemProvider == null) {
			inspectorItemProvider = new InspectorItemProvider(this);
		}

		return inspectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.SpatialEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpatialEntityItemProvider spatialEntityItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.SpatialEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpatialEntityAdapter() {
		if (spatialEntityItemProvider == null) {
			spatialEntityItemProvider = new SpatialEntityItemProvider(this);
		}

		return spatialEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Polygon} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PolygonItemProvider polygonItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Polygon}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPolygonAdapter() {
		if (polygonItemProvider == null) {
			polygonItemProvider = new PolygonItemProvider(this);
		}

		return polygonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Line} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineItemProvider lineItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Line}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineAdapter() {
		if (lineItemProvider == null) {
			lineItemProvider = new LineItemProvider(this);
		}

		return lineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eclipse.emf.abmodel.model.abmodel.Point} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PointItemProvider pointItemProvider;

	/**
	 * This creates an adapter for a {@link eclipse.emf.abmodel.model.abmodel.Point}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPointAdapter() {
		if (pointItemProvider == null) {
			pointItemProvider = new PointItemProvider(this);
		}

		return pointItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (abModelItemProvider != null) abModelItemProvider.dispose();
		if (agentBlockItemProvider != null) agentBlockItemProvider.dispose();
		if (simplePlanItemProvider != null) simplePlanItemProvider.dispose();
		if (globalBlockItemProvider != null) globalBlockItemProvider.dispose();
		if (globalVariableItemProvider != null) globalVariableItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (outputItemProvider != null) outputItemProvider.dispose();
		if (displayItemProvider != null) displayItemProvider.dispose();
		if (planItemProvider != null) planItemProvider.dispose();
		if (monitorItemProvider != null) monitorItemProvider.dispose();
		if (experimentBlockItemProvider != null) experimentBlockItemProvider.dispose();
		if (reflexItemProvider != null) reflexItemProvider.dispose();
		if (complexePlanItemProvider != null) complexePlanItemProvider.dispose();
		if (exportFileItemProvider != null) exportFileItemProvider.dispose();
		if (inspectorItemProvider != null) inspectorItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (spatialEntityItemProvider != null) spatialEntityItemProvider.dispose();
		if (polygonItemProvider != null) polygonItemProvider.dispose();
		if (lineItemProvider != null) lineItemProvider.dispose();
		if (pointItemProvider != null) pointItemProvider.dispose();
	}

}
