/*
 * generated by Xtext 2.25.0
 */
package com.ktsv.asl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AslUiModule extends AbstractAslUiModule {

	public AslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
